[package]
name = "nar20_1"
version = "0.1.7"
authors = ["PtrMan rt09@protonmail.com"]
edition = "2018"

[dependencies]
async-std = "1.6.3"
rand = "0.8.0"

nom = "5"

parking_lot = "0.11.1"


[profile.release]
debug = true