[package]
name = "nar20_1"
version = "0.1.7"
authors = ["PtrMan rt09@protonmail.com"]
edition = "2018"

[dependencies]
async-std = "1.9.0"
rand = "0.8.0"

nom = "6"

parking_lot = "0.11.1"
rusqlite = "0.25.3"

[profile.release]
debug = true